version: '3.8'

services:
  db-restauracja:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@$$w0rd
      POSTGRES_DB: rezerwacje_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: python_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db-restauracja
    environment:
      DATABASE_URL: postgresql://admin:password123@db-restauracja:5432/rezerwacje_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_panel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db-restauracja
      
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
