version: '3.8'

services:
  db-restauracja:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rezerwacje_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_szyna
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: ./backend
    container_name: python_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db-restauracja
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://admin:password123@db-restauracja:5432/rezerwacje_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_panel
    user: root # 
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.pl
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - db-restauracja

  frontend:
    build: ./frontend
    container_name: ztp_frontend
    restart: always
    ports:
      - "5173:5173"


  notification:
    build: ./notification
    container_name: notification_microservice
    restart: always
    depends_on:
      - rabbitmq
  gateway:
    image: nginx:alpine
    container_name: api_gateway
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
    - "5341:80"
    environment:
    - ACCEPT_EULA=Y
    - SEQ_FIRSTRUN_ADMINPASSWORD=admin123

volumes:
  postgres_data:
  seq_data: