events { worker_connections 1024; }

http {
    server {
        listen 5000;

        add_header 'Access-Control-Allow-Origin' 'http://localhost:5173' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'X-Requested-With,Accept,Content-Type,origin' always;

        if ($request_method = 'OPTIONS') {
            return 204;
        }

        location /rezerwacje/ {
            proxy_pass http://backend:8000/rezerwacje/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header Content-Type $http_content_type;
            proxy_set_header Content-Length $http_content_length;

            proxy_pass_request_headers on;
            proxy_pass_request_body on;
        }

        location /dostepnosc-stolikow/ {
            proxy_pass http://backend:8000/dostepnosc-stolikow/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header Content-Type $http_content_type;
            proxy_set_header Content-Length $http_content_length;

            proxy_pass_request_headers on;
            proxy_pass_request_body on;
        }
    }
}
